CREATE TABLE SaleDetails(
Id BIGINT IDENTITY(1,1) NOT NULL,
ProductId BIGINT NOT NULL,
SaleId BIGINT NOT NULL,
ProductQuantity BIGINT NOT NULL,
ProductAmount BIGINT NOT NULL,
CreatedOn DATETIME2(7) NOT NULL,
CreatedBy NVARCHAR(128) NOT NULL

)