CREATE TABLE Sales(

Id BIGINT IDENTITY(1,1) NOT NULL,
SalesDetailsId BIGINT NOT NULL,
TotalAmount DECIMAL(15,8) NOT NULL,
TotalUnits BIGINT NOT NULL,
CustomerKey BIGINT NOT NULL,
CreatedOn DATETIME2 (7) NOT NULL,
);
